### ISSUE TITLE
Welcome to this GitHub project

### ISSUE THREAD

**Issue by donotdespair** [gavwilliams/mcxs-a2-g5#1]
Hi @gavwilliams @alexrendelll and @XinyuDang 

How are you? I hope that you are well! I can see that the project is created and everybody in present. I can't help noticing that you have submitted only one commit thus far. I realise that this does not mean that you are not working and I do not imply that.

In this post, I just wanted to encourage you to the active development of the .Rmd file. On the current. It's the best practice to **commit** and **push to origin** often. Once you do that **fetch the origin** to synchronise the updates from others on your computer. I would expect no problems from you working on this file independently and commiting often. This is exactly where git and Github are great!

All the best, Fellows!

Tomasz

**Comment by gavwilliams** [comment]
Greetings @donotdespair 
Thanks for your message. We have been working on various exercises over the past few days, and now today saving our code in our GitHub repo and establishing the R Markdown file. Your videos have been helpful.
Gavin

**Comment by donotdespair** [comment]
Hey @gavwilliams @alexrendelll and @XinyuDang 

Thank you so much for the collaborative and efficient work on this assignment. It's a pleasure for me to see how you jumped straight into using GitHub facilities to develop your project.

May I have two suggestions:
1. Please, start populating the Rmd file. In a way your extra R file is just a distraction as all of these things can be done in a similar way (just in R code chunks) in Rmd doc. You can also execute individual lines of R code within the chunk by just marking it or simply pressing command+return.
2. I would really ask @XinyuDang to step up and contribute to this project. I am not sure if you are doing work outside of the GitHub repository and I hope you are doing it. But it is essential that you now start developing the Rmd document and contribute to this project on GitHub. 
3. Please, feel free to contact me if you have any questions. The conversations on GitHub work well if I am concerned. Please let me know if they work well for you too.

Keep up the good effort!

Greetings,

Tomasz

**Comment by alexrendelll** [comment]
Hi @donotdespair ,

Thanks for the kind words. I will start transferring everything over to the RMD file shortly as requested!

**Comment by XinyuDang** [comment]
Hi @donotdespair , 

Thank you for the reminder yesterday. I was doing things outside of GitHub for days and have now transferred part of my work into the Rmd document. I will continue to participate on GitHub henceforth. 

With thanks, 
Xinyu Dang

**Comment by donotdespair** [comment]
Hi @XinyuDang PLease, do step in and contribute to the project where it is at the moment. Greetings, @donotdespair

**Comment by donotdespair** [comment]
Hey @gavwilliams @alexrendelll and @XinyuDang  How are you? I am just writing to let you know that I'm closing the issue. I hope you are well! Greetings, Tomasz
