### ISSUE TITLE
Merging Data-Sets + Non-Comformable Matrices

### ISSUE THREAD

**Issue by alexrendelll** [gavwilliams/mcxs-a2-g5#2]
Hi Tomasz ( @donotdespair  ),

Firstly, Ive written a Gibbs Sampler -- but over the last day have been struggling to create the vector of Y variables using the data and thought I should finally reach out to move past this road block. Is there an easier way using the readabs to read multiple series into one table?

Secondly, I was wondering if you could check over the code for the Gibbs sampler as there are some issues in my hyper-parameters for Kappa_A and Kappa_Sigma specifically "alpha_bar_ke" and "s_bar_ka"

**Comment by alexrendelll** [comment]
Ignore the second part of the question -- I have managed to fix that :)

**Comment by donotdespair** [comment]
Hi @alexrendelll reading many series at once is possible but some additional handling of such an object is necessary. I haven't really used this package much - started only this year. Your code seems fine. What's the problem?

If you wanted to play a bit objects `xts` are a bit more advanced than ts. But in the end, whatever works - goes! So if you have it, move on, and maybe you can play more during Assignment 3...

**Comment by alexrendelll** [comment]
Hi @donotdespair ,
Thanks for the feedback I will try that in assignment 3 for sure -- I have just managed to create the X & Y matrices but now am having trouble with the MVIW distribution in the code for the Gibbs sampler. Is it possible for you to take a look?

**Comment by donotdespair** [comment]
@alexrendelll finished with question, but then closed the issue? Still need help with that? I could provide some, but phrase be descriptive of what you are asking for and I'll attend it late in the evening
