### ISSUE TITLE
Creating Vectors of Priors 

### ISSUE THREAD

**Issue by alexrendelll** [gavwilliams/mcxs-a2-g5#3]
I think the current issue with the Gibbs Sampler is that it requires us to input a vector of Prior's . I think we need to add and convert the priors similar to how it is done in Lecture 10 except less complexly. I would think that the process to fixing this issue would look something like : 

1. Looking at the code for L10 below
2. Understanding the required matrix dimensions of -- S_ka, V_ka, alpha_ke , beta_ke, A_, S_, V_
3. Recreating those into the "Prior Matrices" section
4. Updating the coding in the Gibbs Sampler to resemble the input of vectors 

![image](https://user-images.githubusercontent.com/104431159/166096211-a7efbfd8-8f09-4be1-9dc9-f10eee47bd50.png)

**Comment by donotdespair** [comment]
Help wanted from me? If so, please use @donotdespair

**Comment by gavwilliams** [comment]
I think we need to provide prior values for S_ka, V_ka, S_ke, v_ke (this is what @donotdespair did in Assignment 1. Tomasz, do you have any tips for reasonable values for these?

We should use Minnesota prior for A-bar and V-bar like in lecture 8 and what is done in the code for Lecture 10. I have copied this across into our code - it needs tailoring.

With regards to the matrices for prior S-bar and nu-bar, I think we talk about this in Lecture 8 on Slide 11 where the Likelihood function has the distribution matrices of M, P, S, v as seen in the screenshot. priors S-bar = (Y-XAhat)'(Y-XAhat). nu-bar = T-N-K-1
<img width="432" alt="image" src="https://user-images.githubusercontent.com/104430082/166099105-e934e5b5-41bd-46a9-8d50-65c1c2aa3a4a.png">

**Comment by alexrendelll** [comment]
I think you're right Gavin! I am looking into the code for Lecture 9 where the MLE estimation occurs before the prior distribution estimation and trying to implement it but curiously A-Hat is seemingly singular hmmm..

**Comment by alexrendelll** [comment]
Never mind -- I have managed to fix that issue! Now we just need to focus on the creating the vector of priors ( A_ ) which as you said apart of the Minnesota Prior. Creating the vector is slightly confusing though maybe @donotdespair can help. In the code for Lecture 9 under the Prior Distribution section when you're defining "A.prior" can you please explain how you chose to replace "A[2:3,]" with the diagonal matrix I am confused about it

**Comment by donotdespair** [comment]
IF you plug in this A_ matrix into the VAR equation you'll obtain a multivariate random walk process. So that's the interpretation of the prior mean. That's it

**Comment by alexrendelll** [comment]
I see - I think I understand. From what Ive gathered then code should look something like: 
`A_PRIOR           = matrix(0, nrow(A_HAT),nrow(A_HAT))
A_PRIOR[2:11,2:11]= diag(10)` ?

**Comment by donotdespair** [comment]
More like:

`A_PRIOR = matrix(0, nrow(A_HAT),ncol(A_HAT)) A_PRIOR[2:11, ]= diag(10)`
This assumes that your A_HAT is `KxN`

**Comment by gavwilliams** [comment]
Thanks Tomasz!!
