### ISSUE TITLE
Gibbs Sampler

### ISSUE THREAD

**Issue by alexrendelll** [gavwilliams/mcxs-a2-g5#4]
Priors have now been defined using the Minnesota Prior -- issues remain with the coding of the Gibbs Sampler particularly when estimating the MVNIW mean parameter `\hat{A}`. 

Using the formula `V_bar%*%(t(X)%*%Y + diag(1/diag(V_PRIOR*KAPPA_P_A))*hyper[5])` the issue stems from inside the brackets where `X'Y` is 41 x 10 and ` diag(1/diag(V_PRIOR*KAPPA_P_A))*hyper[5])` is 41x41.

**Comment by donotdespair** [comment]
This will be solved if your `* hyper[5]` is replaced by `%*% A_PRIOR`, I guess

**Comment by alexrendelll** [comment]
Hi @donotdespair ! I've spent most of last night and this morning ironing out issues related to the Sampler but I keep getting NAN when trying to run the sampler now could you please take a look and see if there anything you can suggest. I think the issue stems from the "S-bar" variable

**Comment by alexrendelll** [comment]
or maybe the beta_kappa prior.....

**Comment by donotdespair** [comment]
Hi @alexrendelll Yes, I can have a look at it. But can you guide me on what to look at? which file, which lines? And a bit of a description of what's where in this code. Thanks!

**Comment by alexrendelll** [comment]
Hi @donotdespair,

Sure thing! When running trying to run the for loop to create the iterative draws —  it seems to run fine for the first iterations ( I’ve run it line-by-line ) but shortly after it stops due line 176 when calculating S_bar_Chol = chol(S_bar) as S_bar is not positive definite.

Ive tried another method by simply inverting the S_bar and now when drawing from the rWishart distribution it says the scale matrix is not positive-definite.

I have no idea what could be causing this error. Could it be that the hyper-parameter on K_Sigma  - beta_bar_ke is extremely large ( x10 ^ 19 ) ?? ( line 153 ) 


Thanks,
Alex

**Comment by donotdespair** [comment]
1. I believe you should not have a minus here: https://github.com/gavwilliams/mcxs-a2-g5/blob/91c9c4c87b05eadebaf340e3b6b71ad6cbe90334/Assignment_2.R#L150
2. Double and tripple check if your definition of gamma distribution is the same as the one used in the package https://github.com/gavwilliams/mcxs-a2-g5/blob/91c9c4c87b05eadebaf340e3b6b71ad6cbe90334/Assignment_2.R#L154
3. which element of the LHS gets updated here? https://github.com/gavwilliams/mcxs-a2-g5/blob/91c9c4c87b05eadebaf340e3b6b71ad6cbe90334/Assignment_2.R#L155
4. Somewhere here you should have `t(A_POST - A_PRIOR)%*%V_PRIOR_INV%*%(A_POST - A_PRIOR)` but I don't see it. (my notation might not be exact check your derivations). https://github.com/gavwilliams/mcxs-a2-g5/blob/91c9c4c87b05eadebaf340e3b6b71ad6cbe90334/Assignment_2.R#L159
5. CHeck if this line is exactly as it should be (I am not sure anymore): https://github.com/gavwilliams/mcxs-a2-g5/blob/91c9c4c87b05eadebaf340e3b6b71ad6cbe90334/Assignment_2.R#L170

**Comment by alexrendelll** [comment]
Thanks Tomasz, I have now worked made the necessary changes and it seems to be running? .... I think?

**Comment by gavwilliams** [comment]
@donotdespair We are getting posterior draws, so the code for the Gibbs sampler is running from end to end, however the draws we are getting seem extraordinarily large!!
Would you mind taking a look to see whether you can spot any conceptual errors we are making between lines 110 to 176?
Are our initial values for KAPPA_P_A and KAPPA_P_E for Minnesota Prior reasonable?
Thank you!

**Comment by donotdespair** [comment]
Before I go to these 70 lines of code please write me what seems large to you? Please copy/paste your estimates of posterior means for the 10x10 matrix `A_1`. And of the constant term. Send me also the posterior means of `Sigma` and hyper-parameters. How about sending me a sample of trace plots here?

**Comment by gavwilliams** [comment]
Hi @donotdespair  we tried some things to see if we could improve it first before sending but we don't think it improved very much.
Here are our trace plots for A, Sigma and Kappa A and Kappa Sigma. Some of them have very large outliers, or for Kappa_sigma they are all very large. 
My hypothesis is that maybe we are conceptually confusing the Kappas for Minnestor prior and the Kappas for A and Sigma. But that might be only my confusion.
<img width="637" alt="image" src="https://user-images.githubusercontent.com/104430082/166135699-e62fd5a8-9eb4-49cb-86c8-db0984ba7ae1.png">
<img width="632" alt="image" src="https://user-images.githubusercontent.com/104430082/166135702-92fc1bb9-1874-4c7e-936e-12782de27877.png">
<img width="632" alt="image" src="https://user-images.githubusercontent.com/104430082/166135704-64656fcc-6269-4829-b731-cb324196a18e.png">
<img width="629" alt="image" src="https://user-images.githubusercontent.com/104430082/166135712-94564192-ccae-470d-9035-7b9d8dd79053.png">
