### ISSUE TITLE
Extra unnecessary lines from Read-abs series ID in R Mark-down

### ISSUE THREAD

**Issue by gavwilliams** [gavwilliams/mcxs-a2-g5#6]
When we Knit the R Markdown file, it automates many lines of comments per Variable downloaded from ABS. See below. Is there an easy way to remove this, or is it okay to remain? @donotdespair have you seen and addressed this before?
<img width="557" alt="image" src="https://user-images.githubusercontent.com/104430082/166202365-6ad92846-d1a0-49e9-b0f5-d578a48b0955.png">

**Comment by donotdespair** [comment]
Use:
```
```{r message=FALSE}
```

**Comment by donotdespair** [comment]
Maybe with a comma or not. Check it out pls!

**Comment by gavwilliams** [comment]
Great, it works (with comma included!
