### ISSUE TITLE
2D Forecast Graphs

### ISSUE THREAD

**Issue by alexrendelll** [gavwilliams/mcxs-a2-g5#7]
Hi @donotdespair -- I was just wondering if you could talk me through the code for the 2D forecast plots attached below. I seem to understand most of it except for the highlighted parts.

**Comment by alexrendelll** [comment]
![image](https://user-images.githubusercontent.com/104431159/166219690-6e87c34a-2412-44a2-9b64-ab8b1b457612.png)

**Comment by alexrendelll** [comment]
I think y[246,1] is the end of avail sample data period but I am intrigued whaty the rgdp.interval.f[2,20:1] and the [21:1] are doing

**Comment by gavwilliams** [comment]
For reference @donotdespair this is adapted code from your Lecture 9 code. We are struggling to make a visualisation similar to this, to show our forecast for Exercise 11. Any help is appreciated!

cc @alexrendelll

**Comment by donotdespair** [comment]
Hey, this one is fun! PLease feel free to use ggplot ribbon function for an equivalent effect if you are familiar with it. I'm a `base` package person though :)

`polygon` shades the area between the points. You need to provide points in an appropriate sequence. I provide it by specifying:
1. the upper bound (elements 1:20) and the lower bound but in the reverse direction (elements 20:1). Not sure what 21:1 is for anymore, but it must be important :)
